modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT"

issueTrackerURL = "https://github.com/Talia-12/DoHexTheWater/issues"

[[mods]]
modId = "dohexthewater"
version = "${file.jarVersion}"
displayName = "DoHexTheWater"
displayURL = "https://github.com/Talia-12/DoHexTheWater"
logoFile = "logo.png"
credits = "petrak@ and other developers of Hex Casting for the mod that this is an addon for."
authors = "petrak@ (aka gamma-delta)"
description = ""

[[dependencies.dohexthewater]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dohexthewater]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dohexthewater]]
modId = "paucal"
mandatory = true
versionRange = "[0.4.6,0.5.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dohexthewater]]
modId = "patchouli"
mandatory = true
versionRange = "[1.18.2-69,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dohexthewater]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.9.2,)"
ordering = "NONE"
side = "BOTH"
